"""
prompt_service.py
-----------------
Manages per-profile prompt files.

Each profile has:  profiles/<slug>/config/prompts.py
Default prompts:   app/rag/default_prompts.py

The prompts.py file stores ONLY the owner-editable portion of each prompt.
Locked system suffixes (grounding rules, tool protocol, output format, profile
context injection) are defined in LOCKED_PROMPT_SUFFIXES and appended at runtime
by the accessor methods used by ChatService.  Owners never see or edit those parts.

UI operations:
  - view prompts        (editable portion only)
  - edit individual prompts
  - restore to defaults
"""

import ast
import copy
from pathlib import Path
from typing import Optional

from app.core.logging_config import get_logger
from app.rag.default_prompts import (
    PROMPTS as DEFAULT_PROMPTS,
    LOCKED_PROMPT_SUFFIXES,
    UNKNOWN_PHRASES,
    FALLBACK_FOLLOWUPS,
)
from app.storage.file_storage import ProfileFileStorage

logger = get_logger(__name__)

# ── Prompt file template ───────────────────────────────────────────────────────

_PROMPTS_FILE_HEADER = '''\
"""
prompts.py  —  Custom prompts for this profile.

Generated by the Owner/Admin UI. Edit via the UI or directly here.
Restore defaults: Admin UI → Manage Profiles → Prompt Management → Restore Defaults.

NOTE: Only the owner-editable portion of each prompt is stored here.
      System-managed sections (grounding rules, tool protocol, output format)
      are appended at runtime and cannot be modified by profile owners.

Schema:
  PROMPTS = {
    "short_name": {
      "name":       "Human-readable label",
      "short_name": "short_name",
      "content":    "Owner-editable prompt text (use {placeholders} as documented)",
    }
  }
"""

'''

# Anchor strings used to detect and strip locked sections from older prompt
# files that were saved before the editable/locked split was introduced.
# Each list is checked in order; the first match wins.
_MIGRATION_STRIP_ANCHORS: dict[str, list[str]] = {
    "system_prompt":            ["GROUNDING RULES (CRITICAL)"],
    "initial_followups_prompt": ["OUTPUT FORMAT", "- Return ONLY a JSON array", "Full profile overview:"],
    "turn_followups_prompt":    ["OUTPUT FORMAT", "- Return ONLY a JSON array", "Profile overview:"],
}


class PromptService:
    """
    Load and manage per-profile prompts.

    Falls back to default_prompts.py when a profile has no custom file.

    The public accessors (system_prompt, initial_followups_prompt, etc.) return
    the COMPLETE prompt used by the LLM: editable_content + locked_suffix.

    get_prompts() returns only the editable content — used by the owner portal.
    """

    # ── Public: portal-facing ─────────────────────────────────────────────────

    def get_prompts(self, slug: str) -> tuple[dict, bool]:
        """
        Load the EDITABLE portion of prompts for a profile.

        Returns:
            (prompts_dict, is_default) — is_default=True if using defaults.
            The 'content' field in each entry contains only the owner-editable text.
        """
        fs = ProfileFileStorage(slug)
        raw = fs.read_prompts_raw()
        if not raw.strip():
            logger.debug("No custom prompts for '%s' — using defaults", slug)
            return copy.deepcopy(DEFAULT_PROMPTS), True

        parsed = self._parse_prompts_file(raw)
        if parsed is None:
            logger.warning("Failed to parse prompts.py for '%s' — using defaults", slug)
            return copy.deepcopy(DEFAULT_PROMPTS), True

        # Strip any locked suffix that may have been stored in older versions
        for key, entry in parsed.items():
            if isinstance(entry, dict) and "content" in entry:
                entry["content"] = self._strip_locked_suffix(key, entry["content"])

        return parsed, False

    def get_prompt_content(self, slug: str, short_name: str) -> Optional[str]:
        """Get the editable content of a single prompt by short_name."""
        prompts, _ = self.get_prompts(slug)
        entry = prompts.get(short_name)
        return entry.get("content") if entry else None

    def update_prompt(self, slug: str, short_name: str, content: str) -> bool:
        """
        Update a single prompt's editable content and save to prompts.py.
        The locked suffix is NOT stored — it will be re-appended at runtime.
        """
        prompts, is_default = self.get_prompts(slug)
        if short_name not in prompts:
            logger.warning("Unknown prompt key '%s' for profile '%s'", short_name, slug)
            return False

        # Strip locked suffix defensively (in case caller included it)
        content = self._strip_locked_suffix(short_name, content)
        prompts[short_name]["content"] = content
        return self._save_prompts(slug, prompts)

    def restore_defaults(self, slug: str) -> bool:
        """Delete the custom prompts file so defaults are used."""
        fs = ProfileFileStorage(slug)
        try:
            if fs.prompts_path.exists():
                fs.prompts_path.unlink()
                logger.info("Restored default prompts for profile '%s'", slug)
            return True
        except Exception as e:
            logger.error("Failed to restore defaults for '%s': %s", slug, e)
            return False

    def ensure_prompts_file(self, slug: str) -> None:
        """Write default prompts.py if the file doesn't exist (called on profile creation)."""
        fs = ProfileFileStorage(slug)
        if not fs.prompts_path.exists():
            self._save_prompts(slug, copy.deepcopy(DEFAULT_PROMPTS))
            logger.info("Created default prompts file for profile '%s'", slug)

    # ── Public: AI-facing accessors (editable + locked) ───────────────────────
    #
    # Each method returns the COMPLETE prompt used by the LLM:
    #   editable_content (from profile file or default) + locked_suffix
    #
    # Callers always receive a non-empty string — no further None-checks needed.

    def system_prompt(self, slug: str) -> str:
        return self._build(slug, "system_prompt")

    def initial_followups_prompt(self, slug: str) -> str:
        return self._build(slug, "initial_followups_prompt")

    def turn_followups_prompt(self, slug: str) -> str:
        return self._build(slug, "turn_followups_prompt")

    def welcome_message(self, slug: str) -> str:
        # No locked suffix for user-visible text prompts
        return self._get_or_default(slug, "welcome_message")

    def chat_placeholder(self, slug: str) -> str:
        return self._get_or_default(slug, "chat_placeholder")

    def unknown_phrases(self) -> list[str]:
        return UNKNOWN_PHRASES

    def fallback_followups(self) -> list[str]:
        return FALLBACK_FOLLOWUPS

    # ── Private helpers ───────────────────────────────────────────────────────

    def _build(self, slug: str, key: str) -> str:
        """Return editable content + locked suffix for the given prompt key."""
        editable = self._get_or_default(slug, key)
        locked   = LOCKED_PROMPT_SUFFIXES.get(key, "")
        return editable + locked

    def _get_or_default(self, slug: str, key: str) -> str:
        """Return the profile's editable prompt content, or the system default."""
        content = self.get_prompt_content(slug, key)
        if content is not None:
            return content
        default = DEFAULT_PROMPTS.get(key, {}).get("content", "")
        if not default:
            logger.warning("No default prompt found for key='%s'", key)
        return default

    def _strip_locked_suffix(self, key: str, content: str) -> str:
        """
        Remove the locked suffix from stored content if present.

        Handles both the new format (starts with "\nOUTPUT FORMAT") and older
        files saved before the editable/locked split (e.g. content that includes
        "GROUNDING RULES (CRITICAL)" or "Full profile overview:").
        """
        anchors = _MIGRATION_STRIP_ANCHORS.get(key, [])
        for anchor in anchors:
            # Search for anchor as its own line (after a newline)
            idx = content.find("\n" + anchor)
            if idx != -1:
                return content[:idx].rstrip()
        return content

    def _save_prompts(self, slug: str, prompts: dict) -> bool:
        fs = ProfileFileStorage(slug)
        try:
            file_content = _PROMPTS_FILE_HEADER + f"PROMPTS = {repr(prompts)}\n"
            fs.write_prompts_raw(file_content)
            logger.info("Saved prompts for profile '%s'", slug)
            return True
        except Exception as e:
            logger.error("Failed to save prompts for '%s': %s", slug, e)
            return False

    def _parse_prompts_file(self, source: str) -> Optional[dict]:
        """
        Safely parse a prompts.py file using AST (no exec).
        Returns the PROMPTS dict or None on failure.
        """
        try:
            tree = ast.parse(source)
            for node in ast.walk(tree):
                if isinstance(node, ast.Assign):
                    for target in node.targets:
                        if isinstance(target, ast.Name) and target.id == "PROMPTS":
                            return ast.literal_eval(node.value)
        except Exception as e:
            logger.warning("AST parse of prompts file failed: %s", e)
        return None


# Singleton
prompt_service = PromptService()
